from yacs.config import CfgNode as CN

_C = CN()

# ----- BASIC SETTINGS -----
_C.BASIC = CN()
_C.BASIC.NAME = ''
_C.BASIC.RESULT_DIR = ''
_C.BASIC.CLASS_NUM = 4

# ----- DATASET BUILDER -----
_C.DATASET = CN()

_C.DATASET.TEST_IMG_ROOT = ''
_C.DATASET.TEST_BATCHSIZE = 128

_C.DATASET.TRAIN_IMG_ROOT = ''
_C.DATASET.LABEL_BATCHSIZE = 43
_C.DATASET.UNLABEL_BATCHSIZE = 36
_C.DATASET.AUG = ''

# ----- TRAIN BUILDER -----
_C.TRAIN = CN()
_C.TRAIN.EPOCH = 90
_C.TRAIN.NET_TYPE = ''
_C.TRAIN.SSL_TYPE = ''
_C.TRAIN.THRESH_WARMUP = False
_C.TRAIN.THRESHOLD = 0.95   # 伪标签置信度

_C.TRAIN.LOSS = CN()
_C.TRAIN.LOSS.LOSS_TYPE = ''
_C.TRAIN.LOSS.WEIGHT = False

_C.TRAIN.OPTIMIZER = CN()
_C.TRAIN.OPTIMIZER.TYPE = ''
_C.TRAIN.OPTIMIZER.MOMENTUM = 0.9
_C.TRAIN.OPTIMIZER.WEIGHT_DECAY = 0.0
_C.TRAIN.OPTIMIZER.LR_SCHEDULER = 0.0001

_C.TRAIN.SCHEDULER = CN()
_C.TRAIN.SCHEDULER.TYPE = ''
_C.TRAIN.SCHEDULER.PARAMETER_1 = 3
_C.TRAIN.SCHEDULER.PARAMETER_2 = 2

def update_config(cfg, args):
    cfg.defrost()
    cfg.merge_from_file(args)
    cfg.freeze()
