BASIC:
 NAME: FlexMatch.EfficientNet
 RESULT_DIR: /root/autodl-tmp/results/ISIC/
 CLASS_NUM: 7

DATASET:
 TEST_IMG_ROOT: /root/autodl-tmp/DataBase/ISIC/test/
 TEST_BATCHSIZE: 128
 TRAIN_IMG_ROOT: /root/autodl-tmp/DataBase/ISIC/train/
 LABEL_BATCHSIZE: 52
 UNLABEL_BATCHSIZE: 36
 AUG: ''

TRAIN:
 EPOCH: 300                   # 1000
 NET_TYPE: efficientnet-b3    # 务必小写，且带-
 SSL_TYPE: FlexMatch
 THRESH_WARMUP: False
 THRESHOLD: 0.95

 LOSS:
  LOSS_TYPE: CrossEntropy
  WEIGHT: False

 OPTIMIZER:              
  TYPE: SGD                   # SGD
  WEIGHT_DECAY: 0.0           # 不设置就写0，1e-4没有0好
  MOMENTUM: 0.9
  LR_SCHEDULER: 0.001

 SCHEDULER: 
  TYPE: CosineAnnealingWarmRestarts     # Custom\MultiStepLR\StepLR\CosineAnnealingLR\CosineAnnealingWarmRestarts，MultiStepLR更快效果也好
  PARAMETER_1: 3                 # 2\[30, 60]\2.4\50                 
  PARAMETER_2: 2                      # 4\0.1\0.97\0.0001
